### ISSUE TITLE
Please add Kushagra's push access

### ISSUE THREAD

**Issue by Steven-Eardley** [robert-koch-institut/mex-invenio#1]
@cutoffthetop, please add @varadekd as a contributor to this repo.
Cheers!

**Comment by Steven-Eardley** [comment]
Did not mean to close; used the wrong column to add it to the project.

**Comment by Steven-Eardley** [comment]
Resolved, no action required (just an oddity about watchers / tagging autocomplete)

**Comment by cutoffthetop** [comment]
> Resolved, no action required (just an oddity about watchers / tagging autocomplete)

yep, he should already be on board :)
